app/Http/routes.php
<?php
/**
 * @author Bogdan Odarchenko, cto@web2print.pro
 *
 */

/*
 * Авторизация и регистрация
 */
Route::get('/',                     'Auth\AuthController@getLogin')->name('home');
Route::get('auth/login/{email?}',   'Auth\AuthController@getLogin')->name('auth.login');
Route::post('auth/login',           'Auth\AuthController@postLogin')->name('auth.login');
Route::get('auth/logout/{email?}',  'Auth\AuthController@getLogout')->name('auth.logout');
Route::any('auth/login_token/{email}/{login_token}', 'UsersController@loginByToken')->name('auth.login_token');
Route::any('auth/login_token/{email}/{login_token}/approve/{order_id}', 'UsersController@loginByTokenApprove')->name('auth.login_token_approve');
Route::any('auth/login_token/{email}/{login_token}/1', 'UsersController@loginByTokenToPayments');

// Открытая регистрация ?
Route::get('auth/register',         'Auth\RegisterController@getRegister')->name('auth.register');;
Route::post('auth/register',        'Auth\RegisterController@postRegister')->name('auth.register');

Route::get('auth/password/restore',         'Auth\ForgotPasswordController@restore')->name('auth.password.restore');
Route::post('auth/password/restore',        'Auth\ForgotPasswordController@send')->name('auth.password.restore');
Route::get('auth/password/info/{token}',    'Auth\ForgotPasswordController@info')->name('auth.password.info');
Route::get('auth/password/create/{token}',     'Auth\ForgotPasswordController@createPassword')->name('auth.password.create');
Route::get('auth/password/new/{token}',     'Auth\ForgotPasswordController@newPassword')->name('auth.password.new');
Route::post('auth/password/new/{token}',    'Auth\ForgotPasswordController@store')->name('auth.password.store');

/*
 *  Cron
 */
Route::get('/cron/parser/search',   'CrontabController@parserSearch');
Route::get('/cron/parser/parse',    'CrontabController@parserParse');
Route::get('/cron/orders/make/pdf', 'CrontabController@ordersMakePdf');

/*
 * -----------------------------------------------
 *  AUTH USERS
 * -----------------------------------------------
 */

Route::group(['middleware' => ['auth']], function () {

    Route::get('/home', function() {
        if (\Auth::user()->accessLevel() == 1) {
            return redirect('/orders/user_orders/');
        } else {
            return redirect('/orders/history/');
        }
    });
    Route::get('/new-dashboard', 'Dashboard\DashboardController@index');

    /*
     * -----------------------------------------------
     *  ADMIN PANEL (root, admin, manager)
     * -----------------------------------------------
     */

    Route::group(['middleware' => ['is.manager']], function ()
    {
        // Dashboard
        Route::get('/dashboard',    'CrmController@dashboard');

        // Employees
        Route::get('contractors/employees', 'Contractors\EmployeeController@index')->name('contractors.employees');
        Route::post('contractors/employees/create', 'Contractors\EmployeeController@store')->name('contractors.employees.store');
        Route::get('contractors/employees/{user}/edit', 'Contractors\EmployeeController@edit')->name('contractors.employees.edit');
        
        Route::get('contractors/employee/{user}/salary', 'Contractors\EmployeeController@salary')->name('employee.salary');

        /*
         * Group orders
         */
        Route::any('/orders/history/{status?}', 'GroupOrdersController@getGroupOrders')->name('orders.history');

        /*
         * Справочник
         */
        Route::any('/template',                             'TemplateController@index');
        Route::get('/template/upload/{id}',                 'TemplateController@upload');
        Route::get('/template/parse/{id}',                  'TemplateController@parse');
        Route::get('/template/on/{id}',                     'TemplateController@on');
        Route::get('/template/off/{id}',                    'TemplateController@off');
        Route::get('/template/delete/{id}',                 'TemplateController@delete');
        Route::any('/template/new/{client_id}/{type_id}',   'TemplateController@create');
        Route::any('/template/store/{client_id}/{type_id}', 'TemplateController@store');
        Route::get('templates/organize', 'TemplateController@organize')->name('templates.organize');
        Route::patch('templates/organize', 'TemplateController@patchOrganize');
        Route::post('templates/organize/activity', 'TemplateController@collectionActivity');

        Route::any('/products',                         'ProductsController@index');
        Route::post('/products/new',                    'ProductsController@create');
        Route::get('/products/edit/{id}',               'ProductsController@edit');
        Route::post('/products/edit/{id}',              'ProductsController@update');
        Route::get('/products/price/{id}',              'ProductsController@price');
        Route::post('/products/price_save',             'ProductsController@priceSave');
        Route::get('/products/on/{id}',                 'ProductsController@on');
        Route::get('/products/off/{id}',                'ProductsController@off');

        Route::get('/products/types',               'ThemesController@index');
        Route::get('/products/types/delete/{id}',   'ThemesController@delete');
        Route::post('/products/types/new',          'ThemesController@create');
        Route::get('/products/types/edit/{id}',     'ThemesController@edit');
        Route::post('/products/types/edit/{id}',    'ThemesController@update');
        Route::get('/products/types/on/{id}',       'ThemesController@on');
        Route::get('/products/types/off/{id}',      'ThemesController@off');

        Route::get('/client_types',               'ClientTypesController@index')->name('client_types.index');
        Route::get('/client_types/delete/{id}',   'ClientTypesController@delete');
        Route::post('/client_types/new',          'ClientTypesController@create');
        Route::get('/client_types/edit/{id}',     'ClientTypesController@edit');
        Route::post('/client_types/edit/{id}',    'ClientTypesController@update');

        Route::get('/urgency',               'UrgencyController@index')->name('urgency.index');
        Route::get('/urgency/delete/{id}',   'UrgencyController@delete');
        Route::post('/urgency/new',          'UrgencyController@create');
        Route::get('/urgency/edit/{id}',     'UrgencyController@edit');
        Route::post('/urgency/edit/{id}',    'UrgencyController@update');

        Route::get('/payment_types',               'PaymentTypesController@index')->name('payment_types.index');
        Route::get('/payment_types/delete/{id}',   'PaymentTypesController@delete');
        Route::post('/payment_types/new',          'PaymentTypesController@create');
        Route::get('/payment_types/edit/{id}',     'PaymentTypesController@edit');
        Route::post('/payment_types/edit/{id}',    'PaymentTypesController@update');


        Route::get('/delivery_types',              'DeliveryTypesController@index')->name('delivery_types.index');
        Route::get('/delivery_type/delete/{id}',   'DeliveryTypesController@delete');
        Route::post('/delivery_type/new',          'DeliveryTypesController@create');
        Route::get('/delivery_type/edit/{id}',     'DeliveryTypesController@edit');
        Route::post('/delivery_type/edit/{id}',    'DeliveryTypesController@update');
        /*
         * options details
         */
        Route::post('/options/details/new',         'DetailsController@create');
        Route::get('/options/details/edit/{id}',    'DetailsController@edit');
        Route::post('/options/details/edit/{id}',   'DetailsController@update');
        Route::get('/options/details/on/{id}',      'DetailsController@on');
        Route::get('/options/details/off/{id}',     'DetailsController@off');
        Route::post('options/details', 'DetailsController@store')->name('details.store');

        /*
        * options parameters
        */
        Route::post('options/logo', 'ParametersController@logo')->name('settings.logo');
        Route::any('/options/get_inn_data', 'ParametersController@getINNdata');
        Route::any('/options/get_bik_data', 'ParametersController@getBIKdata');

        Route::get('/orders/turn_orders/{filters?}', 'OrdersController@turnOrders');

        /*
         * widgets
         */
        Route::get('/widgets/',                 'WidgetController@index')->name('widgets');
        Route::post('/widget/registration/save', 'WidgetController@saveRegistrationSettings')->name('widget.registration.save');

        // Contractors
        Route::any('contractors/clients', 'Contractors\ClientController@index')->name('contractors.clients');
        Route::resource('contractors', 'Contractors\ContractorsController', [
            'as' => 'contractors'
        ]);

        // intermediary
        Route::resource('intermediary', 'Contractors\IntermediaryController');

        /*
         * Clients
         */
        Route::get('/crm/{filters?}', 'Contractors\ClientController@index');
        Route::get('/crm_ajax/{filters?}', 'Contractors\ClientController@getFilteredClients');
        Route::get('/client/new', 'Contractors\ClientController@create')->name('client.new');
        Route::post('/client/new', 'Contractors\ClientController@store')->name('client.new');
        Route::get('/client/show/{client}', 'Contractors\ClientController@show')->name('client.show');
        Route::post('/client/save/{client}', 'Contractors\ClientController@update')->name('client.update');
        Route::post('/client/save/description/{client}', 'Contractors\ClientController@saveDescription')->name('client.save.description');
        Route::post('/client/saveContact/{contact}', 'Contractors\ClientController@saveContact')->name('client.save.contact');

app/User.php
<?php

namespace App;

use App\Models\Statistic\StatisticClient;
use App\Models\Statistic\StatisticOrder;
use App\Traits\UserRoles;
use App\Traits\UserSalary;
use App\Traits\UserAccruable;
use App\Traits\SubdomainTrait;
use Illuminate\Auth\Authenticatable;
use App\Models\Salary\SalaryOperation;
use App\Traits\LocalizedEloquentDates;
use Illuminate\Database\Eloquent\Model;
use App\Models\Statistic\StatisticInvoice;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword, LocalizedEloquentDates,
        SubdomainTrait, UserRoles, UserSalary;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'lastname', 'email', 'password', 'id_group', 'subdomain_id',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    /**
     * @return mixed
     */
    public function accessLevel() {
        return $this->id_group;
    }

    /**
     * Get full name of the user
     *
     * @return string
     */
    public function getFullNameAttribute()
    {
        return $this->name . ' ' . $this->lastname;
    }

    /**
     * Group of the user
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function group()
    {
        return $this->belongsTo(UserGroup::class, 'id_group');
    }

    /**
     * Check for user belongs to the group
     *
     * @param int|array $groupId
     * @return bool
     */
    public function hasGroup($groupId)
    {
        if (is_array($groupId)) {
            return in_array($this->group->id, $groupId);
        }

        return $this->group->id == $groupId;
    }

    /**
     * Check for user has not group
     *
     * @param $groupId
     * @return bool
     */
    public function hasNotGroup($groupId)
    {
        return ! $this->hasGroup($groupId);
    }

    /**
     * Check for user belongs to the group (by Role name)
     * Example:
     *      $user->is('admin')
     *      $user->is(['admin', 'root'])
     *
     * Magic:
     *      $user->isAdmin();
     *
     * @param int|array $role
     * @return bool
     */
    public function is($role)
    {
        if (is_array($role)) {
            return in_array($this->group->role, $role);
        }

        return $this->group->role == $role;
    }

    /**
     * Check for user is not belongs to the group (by Role name)
     * Example:
     *      $user->isNot('admin')
     *      $user->isNot(['admin', 'root'])
     *
     * Magic:
     *      $user->isNotAdmin();
     *
     * @param int|array $groupId
     * @return bool
     */
    public function isNot($role)
    {
        if (is_array($role)) {
            return ! in_array($this->group->role, $role);
        }

        return $this->group->role != $role;
    }

    /**
     * Contact, related to the user
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function contact()
    {
        return $this->hasOne(Contacts::class);
    }

    /**
     * Client, assigned to the user
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function client()
    {
        return $this->hasOne(Clients::class);
    }

    /**
     * Attachment files by this user
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function files()
    {
        return $this->hasMany(AttachmentFile::class, 'user_id');
    }

    /**
     * Subdomain for user's account
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function subdomain()
    {
        return $this->belongsTo(Subdomain::class);
    }

    /**
     * [displayedName description]
     *
     * @return string
     */
    public function displayedName()
    {
        $name = !is_null($this->contact) ? $this->contact->name : $this->name;
        $lastName = !is_null($this->contact) ? $this->contact->last_name : $this->last_name;

        return $name.' '.$lastName;
    }

    /**
     * Handle dynamic calls into macros or pass missing methods to the store.
     *
     * @param  string  $method
     * @param  array   $arguments
     * @return mixed
     */

    public function __call($method, $arguments)
    {
        $return = $this->handleMagicRole($method, $arguments);
        return (!is_null($return)) ? $return : parent::__call($method, $arguments);
    }

    /**
     * Get user login link
     *
     * @return string
     */
    public function loginLink()
    {
        return url("auth/login_token/{$this->email}/{$this->login_token}");
    }

    /**
     * Ссылка на установление нового пароля
     *
     * @return string
     */
    public function passwordResetLink()
    {
        $passwordReset = PasswordReset::where('email', $this->email)
            ->where('user_id', $this->id)
            ->first();

        return route('auth.password.create', $passwordReset->token);
    }

    /**
     * Scope manager users
     *
     * @param $query
     */
    public function scopeManagers($query)
    {
        $query->where('id_group', UserGroup::MANAGER);
    }

    /**
     * Статистика пользователя по счетам
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function statisticInvoices()
    {
        return $this->hasMany(StatisticInvoice::class, 'manager_id');
    }

    /**
     * Статистика по клиентам
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function statisticClients()
    {
        return $this->hasMany(StatisticClient::class, 'manager_id');
    }

    /**
     * Статистика по заказам
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function statisticOrders()
    {
        return $this->hasMany(StatisticOrder::class, 'manager_id');
    }

    /**
     * Заказы пользователя
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function orders()
    {
        return $this->hasMany(Orders::class, 'manager_id');
    }

    /**
     * Группы заказов пользователя
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function groupOrders()
    {
        return $this->hasMany(GroupOrders::class, 'manager_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function templates()
    {
        return $this->hasMany(TemplateLibrary::class, 'owner_id');
    }

    /**
     * @param string $value
     * @return string
     */
    public function getPhotoAttribute($value)
    {
        $default = asset('images/nophoto.png');

        return $value ? asset('upload/users/'.$value) : $default;
    }
}

resources/views/out.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>MEDIA MOST - группа компаний</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="/plugins/jQuery/jQuery-2.1.4.min.js"></script>
</head>
<!-- ADD THE CLASS layout-top-nav TO REMOVE THE SIDEBAR. -->
<body class="hold-transition skin-blue layout-top-nav">
<div class="wrapper">

    <header class="main-header">
        <nav class="navbar navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <a href="#" class="navbar-brand">MEDIA MOST</a>


                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                    <!--
                                        <ul class="nav navbar-nav">
                                            <li><a href="#">О сервисе <span class="sr-only">(current)</span></a></li>
                                        </ul>
                    -->
                </div><!-- /.navbar-collapse -->

                @if (isset($manager))
                        <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <div style="padding-top:5px; padding-bottom: 0px;color: #fff;">
                                <!-- The user image in the navbar-->
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <p style="float: left;text-align: right;">
                                    Ваш персональный менеджер:&nbsp
                                    <b>@if ($manager->name) {{ $manager->name }} @if ($manager->lastname)  {{ $manager->lastname }} @endif
                                        &nbsp @endif</b>

                                    <br>

                                    @if ($manager->phone)<b> {{ $manager->phone }}</b>, &nbsp @endif

                                    @if ($manager->email) {{ $manager->email }} &nbsp @endif

                                </p>
                                @if ($manager->photo)
                                    &nbsp<img src="/upload/users/{{ $manager->photo }}" class="img-circle"
                                              alt="User Image" style="margin-left: 10px;float: right;width:40px;">
                                @endif

                            </div>
                        </li>
                    </ul>
                </div>
                @endif
            </div>
        </nav>
    </header>

    <div class="content-wrapper" style="background-color: #fff;">
        <div class="container">
            <section class="content-header" style="padding-bottom: 15px">
                @if (isset($order_status))
                    @if ($order_status < 4)
                        <h1 class="center">
                            Страница согласования
                        </h1>
                    @endif
                @else
                    <h1 class="center" style="color:indianred">
                        Ваш аккаунт деактивирован. Обратитесь к Вашему личному менеджеру.
                    </h1>
                @endif
            </section>

            @yield('content')

        </div><!-- /.container -->
    </div><!-- /.content-wrapper -->

</div><!-- ./wrapper -->

<!-- jQuery 2.1.4 -->
<script src="/plugins/jQuery/jQuery-2.1.4.min.js"></script>
<!-- Bootstrap 3.3.5 -->
<script src="/bootstrap/js/bootstrap.min.js"></script>
<!-- SlimScroll -->
<script src="/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="/plugins/fastclick/fastclick.min.js"></script>

<!-- date-range-picker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
<script src="/plugins/daterangepicker/daterangepicker.js"></script>
<!-- bootstrap datepicker -->
<script src="/plugins/datepicker/bootstrap-datepicker.js"></script>

<!-- AdminLTE App -->
<script src="/dist/js/app.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/dist/js/demo.js"></script>

<script type="text/javascript">
    @if (isset($order_id))
        var order_id = '<? echo $order_id ?>';
    @endif

    $(document).ready(function () {
        $('.datepicker').datepicker({
            language: 'ru',
            startDate: '0d',
            format: 'dd.mm.yyyy',
            autoclose: true
        });
    });

    $(document).ready(function () {
        $("iframe").on("load", function () {

            $(this).contents().find(".change_page").click(function () {
                if (uuid) {
                    location.href = '/user/reviwer/see/' + order_id;
                }
            });

            $(this).contents().find(".show_block_div").click(function () {
                $('.bloc_div_overlay').show();
            });

        })
    });
</script>

@yield('scripts_bottom')

</body>
</html>

resources/views/out_loading.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ settings('company_name') }}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<!-- ADD THE CLASS layout-top-nav TO REMOVE THE SIDEBAR. -->
<body class="hold-transition skin-blue layout-top-nav">
<div class="wrapper">

    <header class="main-header">
        <nav class="navbar navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <? if ($_SERVER['HTTP_HOST'] == 'dev.w2p.me') { ?>
                        <a href="http://web2print.pro/" class="navbar-brand">{{ settings('company_name') }}</a>
                    <? } else { ?>
                        <a href="#" class="navbar-brand">{{ settings('company_name') }}</a>
                    <? } ?>

                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse pull-left" id="navbar-collapse">

                </div><!-- /.navbar-collapse -->

                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <div style="padding-top:5px; padding-bottom: 0px;color: #fff;">
                                <!-- The user image in the navbar-->
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                @if (isset($manager) && Auth::user()->isClient())
                                <p style="float: left;text-align: right;">
                                    Ваш персональный менеджер:&nbsp
                                    <b>@if ($manager->name) {{ $manager->name }} @if ($manager->lastname)  {{ $manager->lastname }} @endif
                                        &nbsp @endif</b>

                                    <br>

                                    @if ($manager->phone)<b> {{ $manager->phone }}</b>, &nbsp @endif

                                    @if ($manager->email) {{ $manager->email }} &nbsp @endif

                                </p>
                                @if ($manager->photo)
                                    &nbsp<img src="/upload/users/{{ $manager->photo }}" class="img-circle"
                                              alt="User Image" style="margin-left: 10px;float: right;width:40px;">
                                @endif
                                @endif
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="content-wrapper" style="background-color: #fff;">
        <div class="container">
            <section class="content-header" style="padding-bottom: 15px">


            @yield('content')

        </div><!-- /.container -->
    </div><!-- /.content-wrapper -->

</div><!-- ./wrapper -->

<!-- jQuery 2.1.4 -->
<script src="/plugins/jQuery/jQuery-2.1.4.min.js"></script>
<!-- Bootstrap 3.3.5 -->
<script src="/bootstrap/js/bootstrap.min.js"></script>
<!-- SlimScroll -->
<script src="/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="/plugins/fastclick/fastclick.min.js"></script>

<!-- date-range-picker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
<script src="/plugins/daterangepicker/daterangepicker.js"></script>
<!-- bootstrap datepicker -->
<script src="/plugins/datepicker/bootstrap-datepicker.js"></script>

<!-- AdminLTE App -->
<script src="/dist/js/app.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/dist/js/demo.js"></script>

<script type="text/javascript">
    @if (isset($order_id))
        var $order_id = '<? echo $order_id?>';
    @endif

    $(document).ready(function () {
        $('.datepicker').datepicker({
            language: 'ru',
            startDate: '0d',
            format: 'dd.mm.yyyy',
            autoclose: true
        });
    });

    $(document).ready(function () {
        $("iframe").on("load", function () {

            $(this).contents().find(".change_page").click(function () {
                if ($order_id) {
                    location.href = '/user/reviwer/see/' + $order_id;
                }
            });

            $(this).contents().find(".show_block_div").click(function () {
                $('.bloc_div_overlay').show();
            });

        })
    });
</script>

@yield('scripts_bottom')

</body>
</html>

resources/views/pages.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>MEDIA MOST - группа компаний</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="../../bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="../../plugins/iCheck/square/blue.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  @yield('content')
</html>